language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -q $DJANGO --use-mirrors
  - python setup.py -q install
script:
  - python runtests.py
env:
  - DJANGO=Django>=1.5,<1.6
  - DJANGO=Django==1.6
