language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -q $DJANGO
  - python setup.py -q install
script:
  - python runtests.py
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.11,<2.0"
sudo: false
