language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - pip install -q $DJANGO
  - python setup.py -q install
script:
  - python runtests.py
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
sudo: false
