language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script:
  - django-admin.py test mailer --settings=mailer.settings.test --pythonpath=./src/
env:
  - DJANGO=1.4.9
  - DJANGO=1.5.5
  - DJANGO=1.6
